A new loader (Hourglass) added
mhnpd/react-loader-spinner pull request #154
Opened 2023-06-30 18:19 UTC by farshad-vgr

The new loader (Hourglass) added to src/loader
Hourglass loader passed all the tests successfully
The index.tsx file updated
The version number increased from 5.3.4 to 5.4.4

2023-07-06 09:06 UTC, mhnpd commented on src/loader/Hourglass.tsx
> +// const HourglassRotate =
Can you remove this comments if not used

2023-07-06 09:07 UTC, mhnpd commented on src/loader/Hourglass.tsx
> +// const HourglassRotate =
@farshad-vgr Once remove ready to merge

2023-07-06 09:08 UTC, mhnpd requested changes
Please update as per comment

Also added a documentation as in the code pointer 
https://github.com/mhnpd/react-loader-spinner/blob/docs/docs/components/Radio.mdx

2023-07-06 12:23 UTC, farshad-vgr commented
I removed useless comments and created the hourglass.mdx file in a separate pull request

2023-08-26 15:20 UTC, mhnpd approved these changes

2023-08-26 15:20 UTC, merged